name: Tag Stable

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: aywengo/kafka-brokers-mcp

jobs:
  retag-stable:
    name: Retag version as stable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Wait for version image to be available
        shell: bash
        run: |
          set -euo pipefail
          IMAGE="${IMAGE_NAME}:${{ steps.version.outputs.VERSION }}"
          echo "Waiting for image ${IMAGE} to be available in Docker Hub..."
          for attempt in {1..60}; do
            if docker buildx imagetools inspect "${IMAGE}" > /dev/null 2>&1; then
              echo "Found image: ${IMAGE}"
              break
            fi
            echo "Attempt ${attempt}/60: Image not found yet. Sleeping 10s..."
            sleep 10
          done
          # Final check to fail if still missing
          docker buildx imagetools inspect "${IMAGE}" > /dev/null

      - name: Tag as stable (multi-arch manifest)
        run: |
          docker buildx imagetools create \
            --tag ${IMAGE_NAME}:stable \
            ${IMAGE_NAME}:${{ steps.version.outputs.VERSION }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md


